import { type ClientSchema, a, defineData } from "@aws-amplify/backend";
import { pollSpotify } from "../functions/poll-spotify/resource";

/**
 * Data model for Deep Cuts.
 *
 * There's no Cognito user pool or Identity Pool in this stack — login is
 * handled by Auth.js against Spotify, not Amplify Auth — so records are
 * scoped to a user via `spotifyUserId` and filtered in application code
 * rather than Amplify's owner-based authorization rules.
 *
 * Two callers, two auth strategies:
 *  - The Next.js server (route handlers / server actions / server
 *    components — never client components) uses the API key. Amplify writes
 *    it into amplify_outputs.json, which is only ever imported from
 *    server-only modules, so it's never shipped to the browser.
 *  - The poll-spotify scheduled function is granted schema-wide IAM access
 *    via the top-level `allow.resource(...)` rule below — no key to manage
 *    there at all.
 */
const schema = a
  .schema({
    Artist: a
      .model({
        spotifyUserId: a.string().required(),
        spotifyArtistId: a.string().required(),
        name: a.string().required(),
        imageUrl: a.string(),
        addedAt: a.datetime().required(),
      })
      .authorization((allow) => [allow.publicApiKey()]),

    Album: a
      .model({
        spotifyUserId: a.string().required(),
        spotifyAlbumId: a.string().required(),
        spotifyArtistId: a.string().required(),
        name: a.string().required(),
        artistName: a.string().required(),
        imageUrl: a.string(),
        addedAt: a.datetime().required(),
        // Optional: albums added before this field existed won't have it,
        // so it degrades to hiding the progress indicator rather than
        // needing a migration.
        totalTracks: a.integer(),
        // Set once poll-spotify observes every track played; null/unset means
        // still active. Kept distinct from a hard delete so completed albums
        // stay visible behind the list page's "show completed" toggle.
        completedAt: a.datetime(),
        // Set by resetAlbumProgress when the user resets the whole album.
        // poll-spotify ignores any Spotify recently-played item with
        // played_at at or before this instant, so a play that was already
        // reset doesn't get resurrected as a new ListenEvent on the next
        // poll (Spotify's history is independent of this app's state and
        // keeps returning the same play for a while after it's deleted).
        resetAt: a.datetime(),
      })
      .authorization((allow) => [allow.publicApiKey()]),

    // One row per play, not per track — replaying a track writes another
    // event with a later playedAt rather than updating the existing one
    // (poll-spotify dedupes only on the exact spotifyTrackId+playedAt pair).
    // FUTURE OPTIMIZATION: if this table grows too large, stop tracking
    // every repeat stream — e.g. give ListenEvent a compound identifier on
    // (spotifyUserId, spotifyTrackId) and overwrite playedAt in place —
    // rather than appending a row per play indefinitely.
    ListenEvent: a
      .model({
        spotifyUserId: a.string().required(),
        spotifyTrackId: a.string().required(),
        spotifyAlbumId: a.string(),
        spotifyArtistId: a.string(),
        trackName: a.string().required(),
        playedAt: a.datetime().required(),
      })
      .authorization((allow) => [allow.publicApiKey()])
      // Otherwise every lookup here (list-page aggregate, track-list page,
      // poll-spotify's dedup check) is a full table scan.
      .secondaryIndexes((index) => [
        index("spotifyUserId").sortKeys(["spotifyAlbumId"]),
      ]),

    // Records the boundary set by resetTrackProgress for a single track,
    // mirroring Album.resetAt but scoped to one track instead of the whole
    // album. Keyed by (spotifyUserId, spotifyTrackId) so a repeat reset of
    // the same track is a plain upsert-by-key rather than piling up rows.
    TrackReset: a
      .model({
        spotifyUserId: a.string().required(),
        spotifyAlbumId: a.string().required(),
        spotifyTrackId: a.string().required(),
        resetAt: a.datetime().required(),
      })
      .identifier(["spotifyUserId", "spotifyTrackId"])
      .authorization((allow) => [allow.publicApiKey()])
      // poll-spotify fetches every reset for the user in one query, same as
      // it does for ListenEvent, rather than one get() per matched track.
      .secondaryIndexes((index) => [
        index("spotifyUserId").sortKeys(["spotifyAlbumId"]),
      ]),

    // Keyed by spotifyUserId (rather than an autogenerated id) so writes
    // from auth.ts are a plain upsert-by-key.
    SpotifyAuth: a
      .model({
        spotifyUserId: a.string().required(),
        refreshToken: a.string().required(),
        updatedAt: a.datetime().required(),
      })
      .identifier(["spotifyUserId"])
      .authorization((allow) => [allow.publicApiKey()]),
  })
  .authorization((allow) => [allow.resource(pollSpotify)]);

export type Schema = ClientSchema<typeof schema>;

export const data = defineData({
  schema,
  authorizationModes: {
    defaultAuthorizationMode: "apiKey",
    apiKeyAuthorizationMode: { expiresInDays: 30 },
  },
});
