import "@testing-library/jest-dom/vitest";
import { vi } from "vitest";
import { createMockDataClient } from "@/test/mockDataClient";

// @/lib/amplify-server only resolves against amplify_outputs.json, which is
// generated by the Amplify sandbox and doesn't exist in this (or any CI)
// environment — so it's mocked globally rather than per-file, both to avoid
// repeating this in every test that touches dataClient and so a new test
// file that transitively imports it doesn't crash with "Cannot resolve
// '../../amplify_outputs.json'" for forgetting to mock it locally. Import
// `dataClient` from "@/lib/amplify-server" in a test file to get this mock
// (cast `as unknown as MockDataClient` from "@/test/mockDataClient" to
// configure `.mockResolvedValue(...)` etc. on it) — don't call vi.mock on
// this module yourselves, it's already covered here.
vi.mock("@/lib/amplify-server", () => ({
  dataClient: createMockDataClient(),
}));

// Several modules format/compare dates without an explicit timezone
// (formatDate, statsData's day-key math); pin the test runner to UTC so
// those assertions don't depend on the machine running them.
process.env.TZ = "UTC";
