/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/design/theme/spotifyTheme.ts
 * Command: astryx theme build src/design/theme/spotifyTheme.ts --out src/design/theme/spotify-theme.css
 * Generated: 2026-07-18T02:39:57.752Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Heading' {
  interface XDSHeadingLevelMap {
    '1': true;
    '2': true;
    '3': true;
    '4': true;
    '5': true;
    '6': true;
  }
}

declare module '@astryxdesign/core/Badge' {
  interface XDSBadgeVariantMap {
    'gray': true;
  }
}
