/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/design/theme/spotifyTheme.ts
 * Command: astryx theme build src/design/theme/spotifyTheme.ts --out src/design/theme/spotify-theme.css
 * Generated: 2026-07-12T22:21:50.443Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const neutralIconRegistry: IconRegistry;
export declare const spotifyTheme: DefinedTheme;
