import type { Metadata } from "next";
import { DesignProvider } from "@/design/DesignProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <DesignProvider>{children}</DesignProvider>
      </body>
    </html>
  );
}
